### ISSUE TITLE
No support for pytest-cov 4.x.x?

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [codecov/codecov-cli#238]
The `setup.py` is pinned to 3.* for `pytest-cov`. Is this intentional? `pytest-cov` 4.0.0 was released in Sep 2022, so I wanted to just check there isn't a way to loosen this restriction.

**Comment by giovanni-guidini** [comment]
This should be supported on version [v0.3.0](https://github.com/codecov/codecov-cli/releases/tag/v0.3.0)
