### ISSUE TITLE
.github/codecov.yml not supported automatically by CLI

### ISSUE THREAD

**Issue by cdignam-segment** [codecov/codecov-cli#319]
[The docs site mentions codecov.yml can exist in the `.github/` directory](https://docs.codecov.com/docs/codecov-yaml#can-i-name-the-file-codecovyml), but the CLI only searches the current directory, not `.github/` for a `codecov.yml`

https://github.com/codecov/codecov-cli/blob/775ba4693040b6d2d7201cedf94137b7bb7d69ee/codecov_cli/main.py#L38

**Comment by jbergstroem** [comment]
The typescript library looks for additional permutations which from a `github-actions` perspective would be semver breaking (perhaps intentional with `v4`?):

https://github.com/codecov/uploader/blob/f5613bbf60cf7ee49808dc94fc57716607be98b2/src/helpers/token.ts#L69-L76
