### ISSUE TITLE
CLI seems to fail when it encounters a space in the Path

### ISSUE THREAD

**Issue by vlad-ko** [codecov/codecov-cli#356]
A customer reported an issue with the upload, whenever the CLI finds a path in the file. 
Path:
`/path/dir/API Interface/somedir/file.js` is failing as `Directory <Interface/somedir/file.js> not found`

**Comment by giovanni-guidini** [comment]
Do you have logs for that error? or more info in general. It would be helpful while trying to reproduce the issue.

**Comment by vlad-ko** [comment]
Hi Gio, the only logs I have are in the slack thread. I just didn't want to
post it here for privacy reasons.

Here's the internal link:
https://sentry.slack.com/archives/C061Y14NH6D/p1705632474204979?thread_ts=1705632474.204979&cid=C061Y14NH6D
