### ISSUE TITLE
Option --disable-search does not disable search

### ISSUE THREAD

**Issue by inez** [codecov/codecov-cli#449]
When running codecov cli like this:
```
python3 ../codecov-cli/codecov_cli/main.py --verbose upload-process -t $CODECOV_TOKEN --disable-search --file coverageReportFromUnitTests.xml -r org/repo -C <sha> --git-service github -P <pr> --disable-search --plugin ""
```
it should not perform search for coverage reports inside the current working directory, but it does specifically due to this call https://github.com/codecov/codecov-cli/blob/7432bad76c619e34d6617b578e039e7d733e3f00/codecov_cli/services/upload/file_finder.py#L206 and https://github.com/codecov/codecov-cli/blob/7432bad76c619e34d6617b578e039e7d733e3f00/codecov_cli/services/upload/file_finder.py#L245.

One very imperfect workaround is to create an empty directory and provider it to `-s` option.

**Comment by rohan-at-sentry** [comment]
@eliatcodecov @joseph-sentry @drazisil @thomasrockhu-codecov 

There's a non-zero possibility that this "breaks" existing users - meaning there's a chance that some orgs/repos depend on the current behavior for Codecov to work (stranger things have happened :D)

Nonetheless, my take is that the existing behavior being described here is clearly bugged (and not the original intent) so I think we should fix it. While it may break those who depended on the incorrect behavior, we can work with them to set them up correctly.
