### ISSUE TITLE
"Repository not found" with `--fail-on-error` not exiting with non-zero code

### ISSUE THREAD

**Issue by Syeberman** [codecov/codecov-cli#529]
I'm setting up `codecovcli` for the first time in AppVeyor. It appears that `--fail-on-error` is not being respected when the upload fails with "Repository not found".

I'm running this Powershell script in AppVeyor:

```
.venv/bin/codecovcli do-upload -t $($CODECOV_TOKEN) --fail-on-error --plugin noop --dir coverage.codecov/ --name "AppVeyor $($env:APPVEYOR_BUILD_VERSION)" --flag munit_test
if (! $?) { throw "codecovcli returned an error" }
.venv/bin/codecovcli not-a-real-command
if (! $?) { throw "codecovcli not-a-real-command returned an error" }
```

And getting the following output:

```
info - 2024-10-12 17:25:54,757 -- ci service found: appveyor
info - 2024-10-12 17:25:54,822 -- Found 1 coverage files to report
info - 2024-10-12 17:25:54,823 -- > coverage.codecov/munit_test.lcov
info - 2024-10-12 17:25:55,650 -- Process Upload complete
error - 2024-10-12 17:25:55,651 -- Upload failed: {"message":"Repository not found"}
Usage: codecovcli [OPTIONS] COMMAND [ARGS]...
Try 'codecovcli --help' for help.
Error: No such command 'not-a-real-command'.
Exception: 
Line |
  12 |  if (! $?) { throw "codecovcli not-a-real-command returned an error" }
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | codecovcli not-a-real-command returned an error
Build exited with code 1
```

As you can see, `if (! $?)` is being triggered for `.venv/bin/codecovcli not-a-real-command`, so I know that the way I am calling `codecovcli` and the way I am checking for errors is correct in this environment.

Other details:
- `codecovcli` 0.7.6
- Ubuntu 22.04
- Python 3.12
- [Full build output](https://ci.appveyor.com/project/Syeberman/nohtyp/builds/50783905)

**Comment by joseph-sentry** [comment]
Hi I think the issue here is that the use of `$($CODECOV_TOKEN)` resolved to an empty string so the `--fail-on-error` was parsed as the value of the `-t` option, so `fail-on-error` wasn't actually set during that invocation of the CLI.

**Comment by Syeberman** [comment]
> Hi I think the issue here is that the use of `$($CODECOV_TOKEN)` resolved to an empty string so the `--fail-on-error` was parsed as the value of the `-t` option, so `fail-on-error` wasn't actually set during that invocation of the CLI.

Yes, that was the issue. My apologies for filing this as an issue.
